
- name: Create pgadmin directory
  become: true
  file:
    path: /opt/pgadmin
    state: directory
    owner: root
    group: root
    mode: "711"

- name: Create pgadmin volume
  become: true
  file:
    path: /opt/pgadmin/data
    state: directory
    owner: 5050
    group: 5050
    mode: "755"

- name: Deploy pgadmin container
  become: true
  docker_container:
    name: pgadmin
    image: dpage/pgadmin4
    #auto_remove: true
    ports:
      - "80:80"
    volumes:
      - /opt/pgadmin/data/:/var/lib/pgadmin
    env:
      PUID: '1001'
      GUID: '1001'
      PGADMIN_DEFAULT_EMAIL: "{{ pgadmin_email }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ pgadmin_password }}"
    pull: true
    restart_policy: always
    cap_drop:
      - all
    capabilities:
      - setuid
      - setgid
      - dac_override
      - net_bind_service
    # security_opts:
    #   - no-new-privilege